source 'https://rubygems.org'

gem "middleman"
gem "middleman-favicon-maker"
gem "middleman-deploy"
gem "middleman-smusher"
gem "middleman-minify-html"

gem "wdm", :platforms => [:mswin, :mingw]

gem "susy"
gem "compass-h5bp"
gem "builder"
#gem "image_optim"
#gem "middleman-imageoptim", "~> 0.0.4"

#gem 'oily_png'
#gem 'coffee-filter' # Coffeescript filter for HAML
gem 'mini_magick'
gem 'docile'
gem 'middleman-core'
#gem 'rb-inotify'

# gem 'rspec'
# gem 'cucumber'
# # gem 'angry-pickle'
# gem 'rspec-expectations'



# gem 'spork'
# # gem 'guard-rspec'
# gem 'guard-spork'
# gem 'guard-cucumber'
# gem 'guard-bundler'
# gem 'terminal-notifier-guard'

# gem 'colored'

# gem 'capybara'
# gem 'rb-fsevent'

# gem 'capybara-webkit'

# gem 'awesome_print'
# gem 'better_errors'
# gem 'binding_of_caller'

