// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(app) {
    var auth, logger, mailer;
    auth = require('../auth/models');
    logger = require('../logger');
    mailer = require('../mailer').mailer;
    return app.get('/notifications', decorators.loginRequired, function(req, res) {
      console.log("called notification");
      return res.render('core/profile/notifications');
    });
  };

}).call(this);
