// Generated by CoffeeScript 1.8.0
(function() {
  var Notification, ObjectId, Schema, gridfs, inflection, mongoose;

  mongoose = require('mongoose');

  gridfs = require('../gridfs');

  inflection = require('inflection');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  module.exports.NOTIFICATION_STATE = {
    MESSAGE: [1, 'message'],
    CHANGE_STATUS: [2, 'change_status']
  };

  Notification = new Schema({
    read: {
      type: Boolean,
      "default": false
    },
    type: {
      type: Number,
      "default": NOTIFICATION_STATE.MESSAGE[1],
      required: true
    },
    creator: {
      type: ObjectId,
      required: true
    },
    createAt: {
      type: Date,
      "default": Date.now
    },
    recipient: {
      type: ObjectId,
      required: true
    },
    refertourl: {
      type: String,
      require: true
    }
  });

}).call(this);
